### ISSUE TITLE
Update UML diagram for database

### ISSUE THREAD

**Issue by FilipePintoReis** [NIAEFEUP/feup-exchange-backend#10]

**Comment by FilipePintoReis** [comment]
I thought there was a PR that closed this; 
TODO Check the state of it.

**Comment by EduRibeiro00** [comment]
Review and update the UML diagram, having into account all the entities and concepts that we will need to keep in the database. A previous UML diagram has already been created, we should update the existing one.
For example, we might need to keep in the database what is the datetime of the scheduled execution of the algorithm; that is not on the DB yet.
